name: eman_application
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  flutter_screenutil: ^5.5.4
  device_preview: ^1.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  fluttertoast: ^8.0.8
  arabic_numbers: ^1.0.0
  flutter_custom_clippers: ^2.1.0
  cached_network_image: ^3.2.1


  # hive packages
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^4.7.0

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
